INSERT INTO autore(nome,cognome,datanascita,nazionalita) VALUES
('Italo','Calvino','1923-10-15','Italia'),
('Luigi','Pirandello','1867-06-28','Italia'),
('Giacomo','Leopardi','1798-06-29','Italia'),
('Luca', 'Rossi','1977-04-15','Italia'),
('Dan','Brown','1964-06-22','StatiUniti'),
('Agatha','Christie','1890-09-15','RegnoUnito'),
('Mary','Shelley','1797-08-30','RegnoUnito');

INSERT INTO libro(titololibro,nomeautore,cognomeautore,lingua) VALUES
('Il barone rampante','Italo','Calvino','Italiano'),
('Le citta invisibili','Italo','Calvino','Italiano'),
('Le cosmicomiche','Italo','Calvino','Italiano'),
('Il cavaliere inesistente','Italo','Calvino','Italiano'),
('Marcovaldo','Italo','Calvino','Italiano'),
('Il visconte dimezzato','Italo','Calvino','Italiano'),
('Il fu Mattia Pascal','Luigi','Pirandello','Italiano'),
('Uno, nessuno e centomila','Luigi','Pirandello','Italiano'),
('Novelle per un anno','Luigi','Pirandello','Italiano'),
('I vecchi e i giovani','Luigi','Pirandello','Italiano'),
('Zibaldone','Giacomo','Leopardi','Italiano'),
('Operette Morali','Giacomo','Leopardi','Italiano'),
('Camorra','Luca','Rossi','Italiano'),
('Arrivederci mafia','Luca','Rossi','Italiano'),
('Catturandi','Luca','Rossi','Italiano'),
('I disarmati','Luca','Rossi','Italiano'),
('The Da Vinci code','Dan','Brown','Inglese'),
('Inferno','Dan','Brown','Inglese'),
('The lost symbol','Dan','Brown','Inglese'),
('Angels and demons','Dan','Brown','Inglese'),
('Origin','Dan','Brown','Inglese'),
('The secret adversary','Agatha','Christie','Inglese'),
('The murder of Roger Ackroyd','Agatha','Christie','Inglese'),
('The floating admiral','Agatha','Christie','Inglese'),
('Murder is easy','Agatha','Christie','Inglese'),
('Frankenstein','Mary','Shelley','Inglese'),
('The last man','Mary','Shelley','Inglese'),
('Mathilda','Mary','Shelley','Inglese');

